# Generated by Django 5.2.17 on 2026-08-28 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academy", "0009_quizanswer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="module",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank for older, flat-style courses. Set this to gate the assignment behind its module being unlocked.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="academy.module",
            ),
        ),
        migrations.AlterField(
            model_name="assignmentsubmission",
            name="passed",
            field=models.BooleanField(
                blank=True,
                help_text="Set when reviewing: checked = counts toward progress and unlocks the next assignment; unchecked = student is sent back to the lesson.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="quizanswer",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
