# Generated by Django 5.2.17 on 2026-08-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automation", "0002_bible_verse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailymessagetemplate",
            name="category",
            field=models.CharField(
                choices=[
                    ("learning_reminder", "Daily learning reminder"),
                    ("academy_update", "Academy updates"),
                    ("new_course", "New courses"),
                    ("ai_tip", "AI learning tips"),
                    ("motivation", "Motivation messages"),
                    ("job_opportunity", "New job opportunities"),
                    ("client_request", "Client requests"),
                    ("portfolio_tip", "Portfolio improvement tips"),
                    ("ai_tool", "AI creative tools"),
                    ("productivity", "Daily productivity reminders"),
                    ("hire_suggestion", "Hire creative suggestions"),
                    ("recommended_creative", "Recommended creatives"),
                    ("platform_update", "Platform updates"),
                    ("wallet_reminder", "Wallet reminders"),
                    ("promo", "Promotional offers"),
                    ("daily_bible_verse", "Daily Bible verse"),
                    ("message", "Messages"),
                    ("job", "Jobs"),
                    ("application", "Applications"),
                    ("collaboration", "Collaborations"),
                    ("wallet", "Wallet"),
                    ("payment", "Payments"),
                    ("vtu", "VTU Orders"),
                    ("ai_credit", "AI Credits"),
                    ("system", "System Updates"),
                    ("broadcast", "Announcements"),
                    ("like", "Likes on your work"),
                    ("comment", "Comments on your work"),
                    ("share", "Shares of your work"),
                    ("follow", "New followers"),
                ],
                max_length=32,
            ),
        ),
    ]
