# Generated by Django 5.2.17 on 2026-08-28 18:47

import geniuzlab.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("motion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="motionshowcase",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="motion_showcase/",
                validators=[geniuzlab.validators.validate_image_upload],
            ),
        ),
    ]
