# Generated by Django 5.2.17 on 2026-08-28 18:47

import geniuzlab.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("konnect", "0006_status_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creativeprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="creative_avatars/",
                validators=[geniuzlab.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="follow",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="portfolio/",
                validators=[geniuzlab.validators.validate_image_upload],
            ),
        ),
        migrations.AlterField(
            model_name="projectcomment",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="projectlike",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="projectmedia",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="projectreport",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="projectshare",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="savedproject",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
